# Generated by Django 3.0.6 on 2020-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
