# Generated by Django 3.0.6 on 2020-05-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_wish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
